videoInfo = {
    'id': 'EngW7tLk6R8',
    'title': 'Sample Videos / Dummy Videos For Demo Use',
    #  'formats': [{...}],
    #  'thumbnails': [{...}],
    'thumbnail': 'https://i.ytimg.com/vi/EngW7tLk6R8/maxresdefault.jpg',
    'description': 'Are you looking for videos of different resolution and sizes to test while designing or developing a mobile app?\n\nSample-Videos.com is a 100% FREE service that allows programmers, testers, designers, developers to download sample videos for demo/test use. No matter what video format they use (MP4, FLV, MKV, 3GP); they will be able to test videos on any Smartphone without any hustle. This is a one stop destination for all sample video testing needs. Just search below for the relevant video formats in specific sizes, download them, and start testing.\n\nA mobile screen resolution can be a big challenge when it comes to watching videos online or offline. By testing out videos one can be rest assured regarding the video playback in an app, without annoying the end users. Choose from four different video extensions i.e. 3GP, MKV, FLV, and MP4. The best thing is all of these are free and very easy to download. We provide you with a specific and perfect resolution in all sizes possible with just one simple click. Check out the one which suits your requirements. All you need to do is hit the DOWNLOAD button, and get started.\n\nhttp://www.sample-videos.com/',
    'channel_id': 'UCslZQaLM_VNzwTzr4SAonqw',
    'channel_url': 'https://www.youtube.com/channel/UCslZQaLM_VNzwTzr4SAonqw',
    'duration': 5,
    'view_count': 260959,
    'average_rating': None,
    'age_limit': 0,
    'webpage_url': 'https://www.youtube.com/watch?v=EngW7tLk6R8',
    'categories': ['People & Blogs'],
    'tags': ['Dummy Videos', 'Sample Videos', 'Demo Use', 'mobile screen resolution', 'DOWNLOAD'],
    'playable_in_embed': True,
    'live_status': 'not_live',
    'release_timestamp': None,
    #  '_format_sort_fields': ('quality', 'res', 'fps', 'hdr:12', 'source', 'vcodec', 'channels', 'acodec', 'lang', 'proto'),
    #  'automatic_captions': {...},
    'subtitles': {},
    'comment_count': 5,
    'chapters': None,
    'heatmap': None,
    'like_count': 103,
    'channel': '进出口服务（AHUANG）',
    'channel_follower_count': 61,
    'uploader': '进出口服务（AHUANG）',
    'uploader_id': '@wowromantic8201',
    'uploader_url': 'https://www.youtube.com/@wowromantic8201',
    'upload_date': '20160511',
    'timestamp': 1462977209,
    #  'availability': 'public',
    'original_url': 'https://www.youtube.com/watch?v=EngW7tLk6R8',
    #  'webpage_url_basename': 'watch',
    #  'webpage_url_domain': 'youtube.com',
    #  'extractor': 'youtube',
    #  'extractor_key': 'Youtube',
    #  'playlist': None,
    #  'playlist_index': None,
    #  'display_id': 'EngW7tLk6R8',
    #  'fulltitle': 'Sample Videos / Dummy Videos For Demo Use',
    #  'duration_string': '5',
    #  'release_year': None,
    #  'is_live': False,
    #  'was_live': False,
    #  'requested_subtitles': None,
    #  '_has_drm': None,
    #  'epoch': 1734440046,
    #  'requested_formats': [...],
    'format': '398 - 1280x720 (720p, IOS)+251 - audio only (medium, IOS)',
    'format_id': '398+251',
    'ext': 'webm',
    'protocol': 'https+https',
    'language': 'ru',
    'format_note': '720p, IOS+medium, IOS',
    'filesize_approx': 645982,
    'tbr': 971.372,
    'width': 1280,
    'height': 720,
    'resolution': '1280x720',
    'fps': 25,
    'dynamic_range': 'SDR',
    'vcodec': 'av01.0.05M.08',
    'vbr': 822.261,
    'stretched_ratio': None,
    'aspect_ratio': 1.78,
    'acodec': 'opus',
    'abr': 149.111,
    'asr': 48000,
    'audio_channels': 2,
}
